### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jrvmalik** [SajadMo/ECG-Heartbeat-Classification-seq2seq-model#3]
Hi Sajad

I get the following error when running the code.

```
Traceback (most recent call last):
  File "seq_seq_annot_DS1DS2.py", line 441, in <module>
    main()
  File "seq_seq_annot_DS1DS2.py", line 226, in main
    run_program(args)
  File "seq_seq_annot_DS1DS2.py", line 242, in run_program
    X_train, y_train = read_mitbih(filename, max_time, classes=classes, max_nlabel=50000,trainset=1)
  File "seq_seq_annot_DS1DS2.py", line 78, in read_mitbih
    data = _data[:(len(_data)/ max_time) * max_time, :]
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by MousaviSajad** [comment]
Hi John,

Thank you for your email.

File "seq_seq_annot_DS1DS2.py", line 78, in read_mitbih
 *   data = _data[:(len(_data)/ max_time) * max_time, :]*

Please change the above line of code to:>>>
  data = _data[:int(len(_data)/ max_time) * max_time, :]

Hope, it helps.

Regards,
Sajad
